// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification.sql

package queries

import (
	"context"
	"time"
)

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (token, user_id, email, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateEmailVerificationParams struct {
	Token     string
	UserID    int64
	Email     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createEmailVerification,
		arg.Token,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredEmailVerifications = `-- name: DeleteExpiredEmailVerifications :exec
DELETE FROM email_verifications WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredEmailVerifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredEmailVerifications)
	return err
}

const getEmailVerification = `-- name: GetEmailVerification :one
SELECT token, user_id, email, expires_at, used, created_at FROM email_verifications WHERE token = ? AND used = 0 AND expires_at > ?
`

type GetEmailVerificationParams struct {
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) GetEmailVerification(ctx context.Context, arg GetEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerification, arg.Token, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :execrows
UPDATE email_verifications SET used = 1 WHERE token = ?
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, token string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEmailVerificationUsed, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEmailVerified = `-- name: MarkEmailVerified :execrows
UPDATE users SET email_verified = 1, updated_at = ? WHERE id = ?
`

type MarkEmailVerifiedParams struct {
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEmailVerified, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
