// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package queries

import (
	"context"
	"time"
)

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (token, user_id, email, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreatePasswordResetParams struct {
	Token     string
	UserID    int64
	Email     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset,
		arg.Token,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_resets WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResets)
	return err
}

const getPasswordReset = `-- name: GetPasswordReset :one
SELECT token, user_id, email, expires_at, used, created_at FROM password_resets WHERE token = ? AND used = 0 AND expires_at > ?
`

type GetPasswordResetParams struct {
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) GetPasswordReset(ctx context.Context, arg GetPasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getPasswordReset, arg.Token, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets SET used = 1 WHERE token = ?
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetUsed, token)
	return err
}
