// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateUserParams struct {
	Email     string
	Name      string
	Password  sql.NullString
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Password,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserWithGoogleID = `-- name: CreateUserWithGoogleID :one
INSERT INTO users (email, name, google_id, avatar, email_verified, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateUserWithGoogleIDParams struct {
	Email         string
	Name          string
	GoogleID      sql.NullString
	Avatar        sql.NullString
	EmailVerified bool
	Role          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUserWithGoogleID(ctx context.Context, arg CreateUserWithGoogleIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUserWithGoogleID,
		arg.Email,
		arg.Name,
		arg.GoogleID,
		arg.Avatar,
		arg.EmailVerified,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password, avatar, role, google_id, email_verified, failed_login_attempts, locked_until, created_at, updated_at
FROM users
WHERE email = ?
`

type GetUserByEmailRow struct {
	ID                  int64
	Email               string
	Name                string
	Password            sql.NullString
	Avatar              sql.NullString
	Role                string
	GoogleID            sql.NullString
	EmailVerified       bool
	FailedLoginAttempts int64
	LockedUntil         sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Avatar,
		&i.Role,
		&i.GoogleID,
		&i.EmailVerified,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, name, password, avatar, role, google_id, email_verified, failed_login_attempts, locked_until, created_at, updated_at
FROM users
WHERE google_id = ?
`

type GetUserByGoogleIDRow struct {
	ID                  int64
	Email               string
	Name                string
	Password            sql.NullString
	Avatar              sql.NullString
	Role                string
	GoogleID            sql.NullString
	EmailVerified       bool
	FailedLoginAttempts int64
	LockedUntil         sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (GetUserByGoogleIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i GetUserByGoogleIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Avatar,
		&i.Role,
		&i.GoogleID,
		&i.EmailVerified,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password, avatar, role, google_id, email_verified, failed_login_attempts, locked_until, created_at, updated_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID                  int64
	Email               string
	Name                string
	Password            sql.NullString
	Avatar              sql.NullString
	Role                string
	GoogleID            sql.NullString
	EmailVerified       bool
	FailedLoginAttempts int64
	LockedUntil         sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Avatar,
		&i.Role,
		&i.GoogleID,
		&i.EmailVerified,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :execrows
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1, updated_at = ?
WHERE id = ?
`

type IncrementFailedLoginAttemptsParams struct {
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, arg IncrementFailedLoginAttemptsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementFailedLoginAttempts, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockUserAccount = `-- name: LockUserAccount :execrows
UPDATE users
SET locked_until = ?, updated_at = ?
WHERE id = ?
`

type LockUserAccountParams struct {
	LockedUntil sql.NullTime
	UpdatedAt   time.Time
	ID          int64
}

func (q *Queries) LockUserAccount(ctx context.Context, arg LockUserAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockUserAccount, arg.LockedUntil, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :execrows
UPDATE users
SET failed_login_attempts = 0, locked_until = NULL, updated_at = ?
WHERE id = ?
`

type ResetFailedLoginAttemptsParams struct {
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, arg ResetFailedLoginAttemptsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetFailedLoginAttempts, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserRoleAdmin = `-- name: SetUserRoleAdmin :execrows
UPDATE users
SET role = ?, updated_at = ?
WHERE id = ?
`

type SetUserRoleAdminParams struct {
	Role      string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) SetUserRoleAdmin(ctx context.Context, arg SetUserRoleAdminParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserRoleAdmin, arg.Role, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET name = ?, avatar = ?, email_verified = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Name          string
	Avatar        sql.NullString
	EmailVerified bool
	UpdatedAt     time.Time
	ID            int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Avatar,
		arg.EmailVerified,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserAvatar = `-- name: UpdateUserAvatar :execrows
UPDATE users
SET avatar = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserAvatarParams struct {
	Avatar    sql.NullString
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserAvatar, arg.Avatar, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	Password  sql.NullString
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
